In [2]:
import numpy as np
from time import time

In [6]:
A = np.random.randn(20,20)

In [7]:
A

array([[ 0.43156232,  0.24138299, -1.66985006, -0.72807833,  0.93688679,
         0.24081051, -1.09305135,  0.54998383,  0.34605191,  0.74692699,
         0.62365148,  0.3823325 , -0.81722723, -1.22563363, -0.07078352,
         0.07356918,  0.11521495,  0.50230874, -0.59001625, -1.63654066],
       [ 0.44821206,  1.17442103, -0.49710044,  1.69476773, -1.26843847,
        -0.00383075, -0.29115098,  0.045138  , -0.24005485, -1.47289806,
        -0.40004672,  2.20589377,  0.10854579,  0.88915532,  1.06880718,
         2.49196259,  0.32737103,  1.55956331,  0.12638586, -1.31038119],
       [ 1.62637648,  1.25904813, -0.17970127, -0.34396309,  0.45623617,
         0.51412622, -1.8663117 ,  0.12082371, -0.68504601, -1.59144685,
         0.37761799,  0.88400772,  1.85448217,  0.77908992,  0.34962539,
         0.58082297,  0.65506393,  0.29411101, -1.0545608 , -0.62071307],
       [ 1.1682824 , -2.51098722,  0.81432052, -0.65094069, -1.3577155 ,
        -1.32117211, -1.20342492,  1.32316265, -

In [8]:
A**8

array([[1.20322852e-03, 1.15253281e-05, 6.04532720e+01, 7.89632217e-02,
        5.93604161e-01, 1.13084621e-05, 2.03762627e+00, 8.37142450e-03,
        2.05650629e-04, 9.68780124e-02, 2.28841972e-02, 4.56593485e-04,
        1.98949389e-01, 5.09196416e+00, 6.30169239e-10, 8.58158377e-10,
        3.10506523e-08, 4.05289978e-03, 1.46862788e-02, 5.14534386e+01],
       [1.62880196e-03, 3.61901644e+00, 3.72866364e-03, 6.80583600e+01,
        6.70124126e+00, 4.63739009e-20, 5.16352190e-05, 1.72321091e-11,
        1.10276713e-05, 2.21503973e+01, 6.55972659e-04, 5.60630534e+02,
        1.92709828e-08, 3.90679869e-01, 1.70292252e+00, 1.48707251e+03,
        1.31923436e-04, 3.49964572e+01, 6.51010230e-08, 8.69323052e+00],
       [4.89518021e+01, 6.31449547e+00, 1.08744951e-06, 1.95927210e-04,
        1.87723082e-03, 4.88155329e-03, 1.47188348e+02, 4.54168836e-08,
        4.85018109e-02, 4.11468999e+01, 4.13448499e-04, 3.72948168e-01,
        1.39888269e+02, 1.35737763e-01, 2.23266573e-04, 1.2952

In [9]:
A.ndim

2

In [10]:
A.shape

(20, 20)

In [11]:
A.dtype

dtype('float64')

In [12]:
B = np.linspace(0,10,3)

In [13]:
B

array([ 0.,  5., 10.])

In [22]:
C = np.eye(4)

In [23]:
C

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
D = np.arange(15).reshape(5,3)

In [25]:
D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
E = np.ones_like(D)

In [27]:
E

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [31]:
E.astype(float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
Q = np.arange(20).reshape(5,4)

In [33]:
Q

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
Q[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [41]:
A = np.arange(20).reshape(5,4)
print(A, '\n')

B = A[2:4, 2:]
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[10 11]
 [14 15]]


In [49]:
A = np.array([[1, 1], [2, 2], [3, 3]])
print(A, '\n')
print(np.insert(A, 1, 5,axis =None), '\n') # spłąszcza i wstawia element 5 na indeks 1
print(np.insert(A, 1, 5,axis =1), '\n') #dodaje kolumne "5" na na nową kolumne która będzie indeksem jeden
A
print(np.insert(A, 1, 5, axis=0), '\n')#nowy wierszz 


[[1 1]
 [2 2]
 [3 3]] 

[1 5 1 2 2 3 3] 

[[1 5 1]
 [2 5 2]
 [3 5 3]] 

[[1 1]
 [5 5]
 [2 2]
 [3 3]] 



In [66]:
print(np.append([1, 2, 3], [4, 5, 6]), '\n')
print(np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]]), '\n')
print(np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0))

[1 2 3 4 5 6] 

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
A = np.arange(20).reshape(5,4)
print(A, '\n')

print(np.delete(A, 1, axis=0), '\n')  #usuwa 1 wiersz
print(A, '\n')
print(np.delete(A, [1, 2], 1), '\n') # usuwa kolumny o indeksaach 1 i 2 nie 1 do 2
print(np.delete(A, [1, 2, 5, 7, 9, 12, 17, 19])) # spłaszcza i usuwa elemnty

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]
 [16 19]] 

[ 0  3  4  6  8 10 11 13 14 15 16 18]


In [82]:
A = np.arange(5, 20).reshape((5, 3))
B = np.arange(15).reshape((5, 3))

print(A < B, '\n')
print(A == A, '\n')
print(A == 17, '\n')
print(np.any( A > 17 ), '\n') # prawdziwe, jeśli każdy element z osobna spełnia warunek 
print(np.all( A > 17 )) # prawdziwe jeśli wszystkie elementy spełniają warunek

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]] 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True False False]] 

True 

False


In [83]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(x, '\n')
print(y, '\n')

# łączenie wierszowe
print(np.concatenate((x, y), axis=0), '\n')
print(np.vstack((x,y)), '\n')

# łączenie kolumnowe
print(np.concatenate((x,y.T), axis=1), '\n')
print(np.hstack((x,y.T)))

[[1 2]
 [3 4]] 

[[5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 5]
 [3 4 6]] 

[[1 2 5]
 [3 4 6]]


In [84]:
x = np.arange(9)
print(x, '\n')
print(np.split(x, 3), '\n') # podział na 3 podtablice
print(np.split(x, [2, 4, 7]), '\n') # podział na 4 podtablice o 
                                # wskazanych początkach

x = x.reshape((3, 3))
print(x, '\n')
print(np.split(x, 3, axis=1), '\n')

# podział ze względu na kolumny
x = np.arange(16.0).reshape(4, 4)
print(x, '\n')
print(np.hsplit(x, 2), '\n')
print(np.hsplit(x, [1, 3]), '\n')

# podział ze względu na wiersze
print(np.vsplit(x, 2), '\n')
print(np.vsplit(x, [1, 3]), '\n')

[0 1 2 3 4 5 6 7 8] 

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])] 

[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8])] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])] 

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] 

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])] 

[array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]]), array([[ 1.,  2.],
       [ 5.,  6.],
       [ 9., 10.],
       [13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]])] 

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])] 

[array([[0., 1., 2., 3.]]), array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]])] 



In [86]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([10, 20])
print(A)
result = A * B  # Broadcasting - B jest powielane, aby pasowało do rozmiaru A
print(result)

[[1 2]
 [3 4]
 [5 6]]
[[ 10  40]
 [ 30  80]
 [ 50 120]]


In [88]:
import numpy as np

A = np.array([[1, 2, 3]])
B = np.array([[10], [20], [30]])
result = A + B  # Broadcasting jest możliw
result

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [119]:
import numpy as np

# Tworzenie tablicy 1D
A = np.array([1, 2, 3, 4])
print(A.shape)
# Dodanie nowego wymiaru za pomocą np.newaxis
B = A[np.newaxis, :]
print(B)


(4,)
[[1 2 3 4]]


In [103]:
B = np.array([1,2,3,4])
B

array([1, 2, 3, 4])

In [101]:
import numpy as np

A = np.array([1,2])  

B = A[:,np.newaxis]
B

array([[1],
       [2]])

In [122]:
import numpy as np

# Tworzymy macierz 2x3
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Oryginalna macierz:\n", matrix)
print("Kształt oryginalnej macierzy:", matrix.shape,'\n')  # Wynik: (2, 3)

new_matrix_1 = matrix[np.newaxis, :, :]
print("Nowa macierz (1x2x3):\n", new_matrix_1)
print("Kształt nowej macierzy:", new_matrix_1.shape,'\n')  # Wynik: (1, 2, 3)

new_matrix_2 = matrix[:, np.newaxis, :]
print("Nowa macierz (2x1x3):\n", new_matrix_2)
print("Kształt nowej macierzy:", new_matrix_2.shape,'\n')  # Wynik: (2, 1, 3)



Oryginalna macierz:
 [[1 2 3]
 [4 5 6]]
Kształt oryginalnej macierzy: (2, 3) 

Nowa macierz (1x2x3):
 [[[1 2 3]
  [4 5 6]]]
Kształt nowej macierzy: (1, 2, 3) 

Nowa macierz (2x1x3):
 [[[1 2 3]]

 [[4 5 6]]]
Kształt nowej macierzy: (2, 1, 3) 

